<Project>
  <PropertyGroup>
    <Version>0.0.6</Version>
    <Authors>CobaltumORM contributors</Authors>
    <PackageReadmeFile>PACKAGE_README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)PACKAGE_README.md"
          Pack="true"
          PackagePath="/"
          Visible="false" />
  </ItemGroup>
</Project>
