using System;
using System.Collections.Generic;
using System.Text;

namespace CobaltumOrm.Analysis;

/// <summary>Formats valid Oracle 19c and later migration DDL.</summary>
public sealed class OracleMigrationSqlWriter : ISqlMigrationWriter
{
    private readonly OracleTypeMapper _typeMapper;

    public OracleMigrationSqlWriter()
        : this(new OracleTypeMapper())
    {
    }

    internal OracleMigrationSqlWriter(OracleTypeMapper typeMapper)
    {
        _typeMapper = typeMapper ?? throw new ArgumentNullException(nameof(typeMapper));
    }

    public string FormatColumn(
        string quotedName,
        string sqlType,
        bool? nullable,
        bool primaryKey,
        bool identity)
    {
        RequireText(quotedName, "A quoted Oracle column name is required.", nameof(quotedName));
        RequireSupportedType(sqlType, nameof(sqlType));
        if (identity && !IsIntegerIdentityType(sqlType))
        {
            throw new ArgumentException(
                "Oracle identity columns must use NUMBER(5,0), NUMBER(10,0), or NUMBER(19,0).",
                nameof(sqlType));
        }

        var builder = new StringBuilder();
        builder.Append(quotedName).Append(' ').Append(sqlType);
        if (identity)
        {
            builder.Append(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if (nullable == false || primaryKey)
        {
            builder.Append(" NOT NULL");
        }

        if (primaryKey)
        {
            builder.Append(" PRIMARY KEY");
        }

        return builder.ToString();
    }

    public string CreateTable(string qualifiedTable, IReadOnlyList<string> columns)
    {
        RequireText(qualifiedTable, "A qualified Oracle table name is required.", nameof(qualifiedTable));
        if (columns is null)
        {
            throw new ArgumentNullException(nameof(columns));
        }

        if (columns.Count == 0)
        {
            throw new ArgumentException("CREATE TABLE requires at least one column.", nameof(columns));
        }

        return "CREATE TABLE " + qualifiedTable + " (" + string.Join(", ", columns) + ");";
    }

    public string AddColumn(string qualifiedTable, string column)
    {
        RequireText(qualifiedTable, "A qualified Oracle table name is required.", nameof(qualifiedTable));
        RequireText(column, "An Oracle column definition is required.", nameof(column));
        return "ALTER TABLE " + qualifiedTable + " ADD (" + column + ");";
    }

    public bool TryAlterColumn(
        string qualifiedTable,
        string quotedColumn,
        string? sqlType,
        bool? nullable,
        out string? sql,
        out string? error)
    {
        sql = null;
        error = null;
        if (string.IsNullOrWhiteSpace(qualifiedTable))
        {
            error = "ALTER TABLE MODIFY requires a qualified table name.";
            return false;
        }

        if (string.IsNullOrWhiteSpace(quotedColumn))
        {
            error = "ALTER TABLE MODIFY requires a quoted column name.";
            return false;
        }

        if (sqlType is null && !nullable.HasValue)
        {
            error = "ALTER TABLE MODIFY requires a target SQL type, target nullability, or both.";
            return false;
        }

        if (sqlType is not null)
        {
            if (string.IsNullOrWhiteSpace(sqlType))
            {
                error = "ALTER TABLE MODIFY target SQL type cannot be empty.";
                return false;
            }

            if (!_typeMapper.TryMap(sqlType, out _))
            {
                error = $"Oracle cannot represent the target SQL type '{sqlType}'.";
                return false;
            }
        }

        var definition = new StringBuilder(quotedColumn);
        if (sqlType is not null)
        {
            definition.Append(' ').Append(sqlType);
        }

        if (nullable.HasValue)
        {
            definition.Append(nullable.Value ? " NULL" : " NOT NULL");
        }

        sql = "ALTER TABLE " + qualifiedTable + " MODIFY (" + definition + ");";
        return true;
    }

    public string DropTable(string qualifiedTable)
    {
        RequireText(qualifiedTable, "A qualified Oracle table name is required.", nameof(qualifiedTable));
        return "DROP TABLE " + qualifiedTable + ";";
    }

    public string DropColumn(string qualifiedTable, string quotedColumn)
    {
        RequireText(qualifiedTable, "A qualified Oracle table name is required.", nameof(qualifiedTable));
        RequireText(quotedColumn, "A quoted Oracle column name is required.", nameof(quotedColumn));
        return "ALTER TABLE " + qualifiedTable + " DROP COLUMN " + quotedColumn + ";";
    }

    public string RenameTable(string qualifiedTable, string quotedNewName)
    {
        RequireText(qualifiedTable, "A qualified Oracle table name is required.", nameof(qualifiedTable));
        RequireText(quotedNewName, "A quoted Oracle table name is required.", nameof(quotedNewName));
        return "ALTER TABLE " + qualifiedTable + " RENAME TO " + quotedNewName + ";";
    }

    public string RenameColumn(string qualifiedTable, string quotedOldName, string quotedNewName)
    {
        RequireText(qualifiedTable, "A qualified Oracle table name is required.", nameof(qualifiedTable));
        RequireText(quotedOldName, "A quoted Oracle column name is required.", nameof(quotedOldName));
        RequireText(quotedNewName, "A quoted Oracle column name is required.", nameof(quotedNewName));
        return "ALTER TABLE " + qualifiedTable + " RENAME COLUMN " + quotedOldName +
            " TO " + quotedNewName + ";";
    }

    private void RequireSupportedType(string sqlType, string parameterName)
    {
        RequireText(sqlType, "An Oracle SQL type is required.", parameterName);
        if (!_typeMapper.TryMap(sqlType, out _))
        {
            throw new ArgumentException($"Oracle cannot represent the SQL type '{sqlType}'.", parameterName);
        }
    }

    private bool IsIntegerIdentityType(string sqlType)
    {
        if (!_typeMapper.TryMap(sqlType, out var kind))
        {
            return false;
        }

        return kind == SqlValueKind.Int16 || kind == SqlValueKind.Int32 || kind == SqlValueKind.Int64;
    }

    private static void RequireText(string value, string message, string parameterName)
    {
        if (value is null)
        {
            throw new ArgumentNullException(parameterName);
        }

        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException(message, parameterName);
        }
    }
}
