using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Xunit;

namespace CobaltumOrm.SourceGenerator.Tests;

public sealed class TableCommandTests
{
    private const string UsersDdl =
        "CREATE TABLE users (" +
        "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
        "email varchar(200) NOT NULL, " +
        "display_name varchar(80));";

    [Fact]
    public void GeneratesRecordCommandsForATableWithAnIdentityPrimaryKey()
    {
        var result = Generate("public static class Empty { }", UsersDdl);

        AssertNoProblems(result);
        Assert.Contains(
            "\"INSERT INTO \\\"users\\\" (\\\"email\\\", \\\"display_name\\\") VALUES (@p0, @p1)\"",
            result.GeneratedText,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"UPDATE \\\"users\\\" SET \\\"email\\\" = @p0, \\\"display_name\\\" = @p1 WHERE \\\"id\\\" = @k0\"",
            result.GeneratedText,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"DELETE FROM \\\"users\\\" WHERE \\\"id\\\" = @k0\"",
            result.GeneratedText,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"DELETE FROM \\\"users\\\"\"",
            result.GeneratedText,
            StringComparison.Ordinal);
    }

    [Fact]
    public async Task InsertUpdateAndDeleteBindRecordValuesAsParameters()
    {
        const string consumer = """
            using System.Data.Common;
            using System.Threading.Tasks;
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static async Task<int> Run(DbConnection connection)
                {
                    var record = new UsersRow(7, "alice@example.test", null);
                    var inserted = await connection
                        .Query(Tables.Users.Insert(new UsersInsertRow("alice@example.test", null)))
                        .ExecuteAsync();
                    var updated = await connection.Query(Tables.Users.Update(record)).ExecuteAsync();
                    var deleted = await connection.Query(Tables.Users.Delete(record)).ExecuteAsync();
                    return inserted + updated + deleted;
                }
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var connection = new QueryFakeDbConnection();
        Assert.Equal(3, await Run<int>(result, connection));
        Assert.Equal(3, connection.Commands.Count);

        var insert = connection.Commands[0];
        Assert.Equal(
            "INSERT INTO \"users\" (\"email\", \"display_name\") VALUES (@p0, @p1)",
            insert.CommandText);
        Assert.Equal("alice@example.test", insert.ParameterValues["@p0"].Value);
        Assert.Equal(DbType.String, insert.ParameterValues["@p0"].DbType);
        Assert.Equal(DBNull.Value, insert.ParameterValues["@p1"].Value);

        var update = connection.Commands[1];
        Assert.Equal(
            "UPDATE \"users\" SET \"email\" = @p0, \"display_name\" = @p1 WHERE \"id\" = @k0",
            update.CommandText);
        Assert.Equal(7, update.ParameterValues["@k0"].Value);
        Assert.Equal(DbType.Int32, update.ParameterValues["@k0"].DbType);

        var delete = connection.Commands[2];
        Assert.Equal("DELETE FROM \"users\" WHERE \"id\" = @k0", delete.CommandText);
        Assert.Equal(7, delete.ParameterValues["@k0"].Value);
        Assert.Single(delete.ParameterValues);
        Assert.All(connection.Commands, command => Assert.True(command.WasDisposed));
    }

    [Fact]
    public async Task DeleteWherePassesTheComparedValueAsAParameter()
    {
        const string consumer = """
            using System.Data.Common;
            using System.Threading.Tasks;
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static Task<int> Run(DbConnection connection) =>
                    connection
                        .Query(Tables.Users.DeleteWhere(Tables.Users.Email.Equal("Robert'); DROP TABLE users; --")))
                        .ExecuteAsync();
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var connection = new QueryFakeDbConnection();
        Assert.Equal(1, await Run<int>(result, connection));

        var command = Assert.Single(connection.Commands);
        Assert.Equal(
            "DELETE FROM \"users\" WHERE \"email\" = @__cobaltum_where_0",
            command.CommandText);
        Assert.Equal(
            "Robert'); DROP TABLE users; --",
            command.ParameterValues["@__cobaltum_where_0"].Value);
    }

    [Fact]
    public async Task DeleteWhereComparesAgainstNullWithoutAddingAParameter()
    {
        const string consumer = """
            using System.Data.Common;
            using System.Threading.Tasks;
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static Task<int> Run(DbConnection connection) =>
                    connection
                        .Query(Tables.Users.DeleteWhere(Tables.Users.DisplayName.Equal(null)))
                        .ExecuteAsync();
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var connection = new QueryFakeDbConnection();
        Assert.Equal(1, await Run<int>(result, connection));

        var command = Assert.Single(connection.Commands);
        Assert.Equal("DELETE FROM \"users\" WHERE \"display_name\" IS NULL", command.CommandText);
        Assert.Empty(command.ParameterValues);
    }

    [Fact]
    public async Task InsertReturningMaterializesTheStoredRecord()
    {
        const string consumer = """
            using System.Data.Common;
            using System.Threading.Tasks;
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static async Task<int> Run(DbConnection connection)
                {
                    var rows = await connection
                        .Query(Tables.Users.InsertReturning(new UsersInsertRow("alice@example.test", null)))
                        .ReadAsync();
                    return rows[0].Id;
                }
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var connection = QueryFakeDbConnection.WithColumns(
            new[] { "id", "email", "display_name" },
            new object?[] { 42, "alice@example.test", DBNull.Value });
        Assert.Equal(42, await Run<int>(result, connection));

        var command = Assert.Single(connection.Commands);
        Assert.Equal(
            "INSERT INTO \"users\" (\"email\", \"display_name\") VALUES (@p0, @p1) " +
            "RETURNING \"id\", \"email\", \"display_name\"",
            command.CommandText);
    }

    [Fact]
    public void InsertReturningRejectsATrailingWhereClause()
    {
        const string consumer = """
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static CobaltumQueryDefinition<UsersRow> Run() =>
                    Tables.Users
                        .InsertReturning(new UsersInsertRow("alice@example.test", null))
                        .Where(Tables.Users.Id.Equal(1));
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var consumerType = result.EmitAndLoad().GetType("TestApp.Consumer", throwOnError: true)!;
        var exception = Assert.Throws<TargetInvocationException>(
            () => consumerType.GetMethod("Run")!.Invoke(null, null));

        Assert.IsType<NotSupportedException>(exception.InnerException);
    }

    [Theory]
    [InlineData("PostgreSql", "VALUES (@p0, @p1) RETURNING \\\"id\\\", \\\"email\\\", \\\"display_name\\\"")]
    [InlineData("Sqlite", "VALUES (@p0, @p1) RETURNING \\\"id\\\", \\\"email\\\", \\\"display_name\\\"")]
    [InlineData(
        "SqlServer",
        "OUTPUT INSERTED.[id], INSERTED.[email], INSERTED.[display_name] VALUES (@p0, @p1)")]
    public void InsertReturningUsesTheStatementFormOfEachProvider(string provider, string expected)
    {
        var result = Generate("public static class Empty { }", ProviderDdl(provider), provider);

        AssertNoProblems(result);
        Assert.Contains("InsertReturning(", result.GeneratedText, StringComparison.Ordinal);
        Assert.Contains(expected, result.GeneratedText, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("MySql")]
    [InlineData("Oracle")]
    public void ProvidersWithoutAGeneratedReturningFormGetInsertOnly(string provider)
    {
        var result = Generate("public static class Empty { }", ProviderDdl(provider), provider);

        AssertNoProblems(result);
        Assert.Contains("Insert(", result.GeneratedText, StringComparison.Ordinal);
        Assert.DoesNotContain("InsertReturning(", result.GeneratedText, StringComparison.Ordinal);
    }

    [Fact]
    public void OracleCommandsUseTheColonParameterPrefix()
    {
        var result = Generate("public static class Empty { }", ProviderDdl("Oracle"), "Oracle");

        AssertNoProblems(result);
        Assert.Contains("VALUES (:p0, :p1)", result.GeneratedText, StringComparison.Ordinal);
        Assert.Contains("WHERE \\\"ID\\\" = :k0", result.GeneratedText, StringComparison.Ordinal);
    }

    [Fact]
    public void ATableWithoutAPrimaryKeyGetsNoRecordUpdateOrDelete()
    {
        var result = Generate(
            "public static class Empty { }",
            "CREATE TABLE events (name text NOT NULL, payload text);");

        AssertNoProblems(result);
        Assert.Contains("CobaltumCommandDefinition Insert(", result.GeneratedText, StringComparison.Ordinal);
        Assert.DoesNotContain("CobaltumCommandDefinition Update(", result.GeneratedText, StringComparison.Ordinal);
        Assert.DoesNotContain("CobaltumCommandDefinition Delete(", result.GeneratedText, StringComparison.Ordinal);
    }

    [Fact]
    public void ATableWhoseColumnsAreAllPrimaryKeyGetsNoRecordUpdate()
    {
        var result = Generate(
            "public static class Empty { }",
            "CREATE TABLE memberships (group_id integer NOT NULL, user_id integer NOT NULL, " +
            "PRIMARY KEY (group_id, user_id));");

        AssertNoProblems(result);
        Assert.DoesNotContain("CobaltumCommandDefinition Update(", result.GeneratedText, StringComparison.Ordinal);
        Assert.Contains(
            "\"DELETE FROM \\\"memberships\\\" WHERE \\\"group_id\\\" = @k0 AND \\\"user_id\\\" = @k1\"",
            result.GeneratedText,
            StringComparison.Ordinal);
        Assert.Contains(
            "\"INSERT INTO \\\"memberships\\\" (\\\"group_id\\\", \\\"user_id\\\") VALUES (@p0, @p1)\"",
            result.GeneratedText,
            StringComparison.Ordinal);
    }

    [Fact]
    public void ColumnsNamedAfterACommandMemberAreRenamed()
    {
        var result = Generate(
            "public static class Empty { }",
            "CREATE TABLE audits (id integer PRIMARY KEY, insert text, delete_where text);");

        AssertNoProblems(result);
        Assert.Contains("Insert_2", result.GeneratedText, StringComparison.Ordinal);
        Assert.Contains("DeleteWhere_2", result.GeneratedText, StringComparison.Ordinal);
    }

    [Fact]
    public void PostgreSqlJsonColumnsKeepTheirParameterConfigurationInRecordCommands()
    {
        var result = Generate(
            "public static class Empty { }",
            "CREATE TABLE documents (id integer PRIMARY KEY, body jsonb NOT NULL);");

        AssertNoProblems(result);
        var insert = result.GeneratedText
            .Split('\n')
            .Single(line => line.Contains("\"@p0\", record.Body", StringComparison.Ordinal));
        Assert.Contains("AddConfigured", insert, StringComparison.Ordinal);
        Assert.Contains("DataTypeName = \"jsonb\"", insert, StringComparison.Ordinal);
    }

    [Fact]
    public void GeneratesAnInsertRecordWithoutTheColumnsTheDatabaseAssigns()
    {
        var result = Generate("public static class Empty { }", UsersDdl);

        AssertNoProblems(result);
        var record = result.GeneratedText
            .Split(new[] { "public sealed record UsersInsertRow(" }, StringSplitOptions.None)[1]
            .Split(new[] { ");" }, StringSplitOptions.None)[0];
        Assert.Contains("global::System.String Email", record, StringComparison.Ordinal);
        Assert.Contains("global::System.String? DisplayName", record, StringComparison.Ordinal);
        Assert.DoesNotContain("Id", record, StringComparison.Ordinal);
        Assert.Contains(
            "public global::CobaltumOrm.CobaltumCommandDefinition Insert(UsersInsertRow record)",
            result.GeneratedText,
            StringComparison.Ordinal);
    }

    [Fact]
    public void KeepsPrimaryKeyColumnsTheApplicationSuppliesInTheInsertRecord()
    {
        var result = Generate(
            "public static class Empty { }",
            "CREATE TABLE tenants (code varchar(20) PRIMARY KEY, label varchar(80) NOT NULL);");

        AssertNoProblems(result);
        var record = result.GeneratedText
            .Split(new[] { "public sealed record TenantsInsertRow(" }, StringSplitOptions.None)[1]
            .Split(new[] { ");" }, StringSplitOptions.None)[0];
        Assert.Contains("global::System.String Code", record, StringComparison.Ordinal);
        Assert.Contains("global::System.String Label", record, StringComparison.Ordinal);
    }

    [Fact]
    public async Task DeleteWhereCombinesConditionsWithAndOr()
    {
        const string consumer = """
            using System.Data.Common;
            using System.Threading.Tasks;
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static Task<int> Run(DbConnection connection) =>
                    connection
                        .Query(Tables.Users.DeleteWhere(
                            (Tables.Users.Email.Like("%@example.test") | Tables.Users.Id.In(1, 2))
                                & Tables.Users.DisplayName.IsNull()))
                        .ExecuteAsync();
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var connection = new QueryFakeDbConnection();
        Assert.Equal(1, await Run<int>(result, connection));

        var command = Assert.Single(connection.Commands);
        Assert.Equal(
            "DELETE FROM \"users\" WHERE ((\"email\" LIKE @__cobaltum_where_0 " +
            "OR \"id\" IN (@__cobaltum_where_1, @__cobaltum_where_2)) " +
            "AND \"display_name\" IS NULL)",
            command.CommandText);
        Assert.Equal("%@example.test", command.ParameterValues["@__cobaltum_where_0"].Value);
        Assert.Equal(1, command.ParameterValues["@__cobaltum_where_1"].Value);
        Assert.Equal(2, command.ParameterValues["@__cobaltum_where_2"].Value);
        Assert.Equal(DbType.Int32, command.ParameterValues["@__cobaltum_where_2"].DbType);
        Assert.Equal(3, command.ParameterValues.Count);
    }

    [Fact]
    public async Task WhereCombinesComparisonsOnAGeneratedTable()
    {
        const string consumer = """
            using System.Data.Common;
            using System.Threading.Tasks;
            using CobaltumOrm;
            using TestApp.Generated;

            namespace TestApp;

            public static class Consumer
            {
                public static async Task<int> Run(DbConnection connection)
                {
                    var rows = await connection
                        .Query(Tables.Users
                            .Where(Tables.Users.Id > 5 & Tables.Users.Id <= 10)
                            .Where(Tables.Users.Email.NotEqual("root@example.test")))
                        .ReadAsync();
                    return rows.Count;
                }
            }
            """;
        var result = Generate(consumer, UsersDdl);

        AssertNoProblems(result);
        var connection = QueryFakeDbConnection.WithColumns(
            new[] { "id", "email", "display_name" },
            new object?[] { 7, "alice@example.test", DBNull.Value });
        Assert.Equal(1, await Run<int>(result, connection));

        var command = Assert.Single(connection.Commands);
        Assert.Equal(
            "SELECT \"id\", \"email\", \"display_name\" FROM \"users\" " +
            "WHERE (\"id\" > @__cobaltum_where_0 AND \"id\" <= @__cobaltum_where_1) " +
            "AND \"email\" <> @__cobaltum_where_2",
            command.CommandText);
        Assert.Equal(5, command.ParameterValues["@__cobaltum_where_0"].Value);
        Assert.Equal(10, command.ParameterValues["@__cobaltum_where_1"].Value);
        Assert.Equal("root@example.test", command.ParameterValues["@__cobaltum_where_2"].Value);
    }

    private static string ProviderDdl(string provider) => provider switch
    {
        "MySql" => "CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, " +
            "`email` varchar(200) NOT NULL, `display_name` varchar(80));",
        "Sqlite" => "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, " +
            "email TEXT NOT NULL, display_name TEXT);",
        "SqlServer" => "CREATE TABLE users (id int IDENTITY(1,1) NOT NULL PRIMARY KEY, " +
            "email nvarchar(200) NOT NULL, display_name nvarchar(80));",
        "Oracle" => "CREATE TABLE \"USERS\" (\"ID\" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY " +
            "NOT NULL PRIMARY KEY, \"EMAIL\" VARCHAR2(200) NOT NULL, \"DISPLAY_NAME\" VARCHAR2(80))",
        _ => UsersDdl,
    };

    private static GeneratorTestResult Generate(string source, string ddl, string? provider = null) =>
        GeneratorTestHost.Run(
            source,
            new[] { ("/db/V1__schema.sql", ddl) },
            databaseProvider: provider,
            analysisCacheEnabled: false);

    private static async Task<T> Run<T>(GeneratorTestResult result, QueryFakeDbConnection connection)
    {
        var consumer = result.EmitAndLoad().GetType("TestApp.Consumer", throwOnError: true)!;
        var task = Assert.IsAssignableFrom<Task<T>>(
            consumer.GetMethod("Run")!.Invoke(null, new object[] { connection }));
        return await task;
    }

    private static void AssertNoProblems(GeneratorTestResult result)
    {
        var problems = result.AllDiagnostics
            .Where(item => item.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .ToArray();
        Assert.True(problems.Length == 0, string.Join(Environment.NewLine, problems.Select(item => item.ToString())));
    }
}
