using System;
using System.Linq;
using Xunit;

namespace CobaltumOrm.Analysis.Tests;

public sealed class DdlMigrationTests
{
    [Fact]
    public void CreatesQuotedAndUnquotedTablesAcrossCommentedStatements()
    {
        const string sql = @"
            -- Flyway comments may sit between statements.
            CREATE TABLE ""Users"" (
                ""Id"" serial PRIMARY KEY,
                ""display name"" VARCHAR(80) NULL,
                amount NUMERIC(12, 2) DEFAULT mystery_function(1.2, 1) NOT NULL,
                created_at TIMESTAMP(3) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
            /* A block comment, including a nested /* comment */, is ignored. */
            CREATE TABLE IF NOT EXISTS audit_log (
                id BIGSERIAL NOT NULL,
                message text DEFAULT 'contains ; and -- text'
            );";

        var result = PostgreSqlMigrationAnalyzer.Analyze(new DatabaseSchema(Array.Empty<Table>()), sql);

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        var users = Assert.Single(result.Schema.Tables, item => item.Name == "Users");
        Assert.Equal(4, users.Columns.Count);
        Assert.Equal("Id", users.Columns[0].Name);
        Assert.Equal("serial", users.Columns[0].SqlType);
        Assert.False(users.Columns[0].IsNullable);
        Assert.True(users.Columns[0].IsPrimaryKey);
        Assert.Equal("varchar(80)", users.Columns[1].SqlType);
        Assert.True(users.Columns[1].IsNullable);
        Assert.Equal("numeric(12,2)", users.Columns[2].SqlType);
        Assert.False(users.Columns[2].IsNullable);
        Assert.Equal("mystery_function(1.2, 1)", users.Columns[2].DefaultExpression);
        Assert.Equal("timestamp(3) with time zone", users.Columns[3].SqlType);
        Assert.NotNull(Assert.Single(result.Schema.Tables, item => item.Name == "audit_log"));
    }

    [Fact]
    public void SerialTypesProduceIntegerClrShapes()
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            "CREATE TABLE ids (small smallserial NOT NULL, normal serial NOT NULL, large bigserial NOT NULL);" );

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        var query = QueryAnalyzer.Analyze(result.Schema, "SELECT small, normal, large FROM ids");

        TestSchema.AssertColumns(query, ("small", "short"), ("normal", "int"), ("large", "long"));
    }

    [Fact]
    public void IdentityColumnsAreIncludedInTheSchema()
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            "CREATE TABLE ids (normal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "strict bigint GENERATED ALWAYS AS IDENTITY NOT NULL);");

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        var table = Assert.Single(result.Schema.Tables);
        Assert.True(table.Columns[0].IsPrimaryKey);
        Assert.False(table.Columns[0].IsNullable);
        Assert.True(table.Columns[0].IsIdentity);
        Assert.Equal("bigint", table.Columns[1].SqlType);
        Assert.False(table.Columns[1].IsNullable);
        Assert.True(table.Columns[1].IsIdentity);
    }

    [Theory]
    [InlineData("json")]
    [InlineData("jsonb")]
    public void JsonTypesUseProviderNeutralStringShape(string sqlType)
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            $"CREATE TABLE documents (payload {sqlType} NOT NULL);");

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        var query = QueryAnalyzer.Analyze(result.Schema, "SELECT payload FROM documents");
        TestSchema.AssertColumns(query, ("payload", "string"));
    }

    [Fact]
    public void AppliesTableEvolutionWithoutChangingTheInputSchema()
    {
        var initial = new DatabaseSchema(new[]
        {
            new Table("accounts", new[]
            {
                new Column("id", "integer"),
                new Column("name", "text"),
            }),
        });

        var result = PostgreSqlMigrationAnalyzer.Analyze(initial, @"
            ALTER TABLE accounts ADD COLUMN created_at timestamptz DEFAULT now() NOT NULL;
            ALTER TABLE accounts ALTER COLUMN name SET NOT NULL;
            ALTER TABLE accounts ALTER COLUMN created_at TYPE timestamp;
            ALTER TABLE accounts RENAME COLUMN name TO display_name;
            ALTER TABLE accounts RENAME TO users;
            ALTER TABLE users ALTER COLUMN display_name DROP NOT NULL;
            ALTER TABLE users ALTER COLUMN display_name SET NOT NULL;
            ALTER TABLE users DROP COLUMN id;");

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        Assert.Equal("accounts", initial.Tables[0].Name);
        Assert.Equal(2, initial.Tables[0].Columns.Count);
        var users = Assert.Single(result.Schema.Tables);
        Assert.Equal("users", users.Name);
        Assert.Equal(2, users.Columns.Count);
        Assert.Equal("display_name", users.Columns[0].Name);
        Assert.False(users.Columns[0].IsNullable);
        Assert.Equal("created_at", users.Columns[1].Name);
        Assert.Equal("timestamp", users.Columns[1].SqlType);
        Assert.False(users.Columns[1].IsNullable);
        Assert.Equal("now()", users.Columns[1].DefaultExpression);
    }

    [Theory]
    [InlineData("CREATE TABLE things (id integer);", "DDL200")]
    [InlineData("DROP TABLE missing;", "DDL201")]
    [InlineData("ALTER TABLE missing ADD COLUMN id integer;", "DDL202")]
    [InlineData("CREATE TABLE things (id time with time zone);", "DDL205")]
    [InlineData("ALTER TABLE things DROP COLUMN missing;", "DDL204")]
    [InlineData("ALTER TABLE things RENAME COLUMN missing TO other;", "DDL204")]
    public void DiagnosesSchemaInvalidChangesWithSourceSpans(string sql, string expectedCode)
    {
        var schema = sql.Contains("time with time zone", System.StringComparison.Ordinal)
            ? new DatabaseSchema(Array.Empty<Table>())
            : new DatabaseSchema(new[]
            {
                new Table("things", new[] { new Column("id", "integer") }),
            });

        var result = PostgreSqlMigrationAnalyzer.Analyze(schema, sql);

        var diagnostic = Assert.Single(result.Diagnostics, item => item.Code == expectedCode);
        Assert.InRange(diagnostic.Span.Start, 0, sql.Length);
        Assert.InRange(diagnostic.Span.Length, 0, sql.Length - diagnostic.Span.Start);
    }

    [Fact]
    public void SupportsConditionalCreateAndDropAsNoOps()
    {
        var schema = new DatabaseSchema(new[]
        {
            new Table("things", new[] { new Column("id", "integer") }),
        });

        var result = PostgreSqlMigrationAnalyzer.Analyze(schema, @"
            CREATE TABLE IF NOT EXISTS things (changed text);
            DROP TABLE IF EXISTS missing;
            ALTER TABLE things ADD COLUMN IF NOT EXISTS id text;");

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        var things = Assert.Single(result.Schema.Tables);
        Assert.Single(things.Columns);
        Assert.Equal("integer", things.Columns[0].SqlType);
    }

    [Fact]
    public void AppliesCompositePrimaryKeysAndDropsExistingTables()
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(new DatabaseSchema(Array.Empty<Table>()), @"
            CREATE TABLE memberships (
                user_id integer,
                group_id integer,
                PRIMARY KEY (user_id, group_id)
            );
            DROP TABLE memberships;");

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        Assert.Empty(result.Schema.Tables);

        var created = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            "CREATE TABLE memberships (user_id integer, group_id integer, PRIMARY KEY (user_id, group_id));");
        var table = Assert.Single(created.Schema.Tables);
        Assert.All(table.Columns, column => Assert.True(column.IsPrimaryKey));
        Assert.All(table.Columns, column => Assert.False(column.IsNullable));
    }

    [Fact]
    public void ReturnsDiagnosticsInsteadOfThrowingForMalformedMigration()
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(new DatabaseSchema(Array.Empty<Table>()), "CREATE TABLE broken (id text;");

        Assert.True(result.HasErrors);
        Assert.NotEmpty(result.Diagnostics);
        Assert.NotNull(result.Schema);
    }

    [Fact]
    public void RejectsCreateTableWithoutColumns()
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            "CREATE TABLE empty ();" );

        Assert.Contains(result.Diagnostics, item => item.Code == "DDL208");
        Assert.Empty(result.Schema.Tables);
    }

    [Fact]
    public void RejectsAddingASecondPrimaryKey()
    {
        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(new[]
            {
                new Table("users", new[] { new Column("id", "integer", false, true) }),
            }),
            "ALTER TABLE users ADD COLUMN tenant_id integer PRIMARY KEY;" );

        Assert.Contains(result.Diagnostics, item => item.Code == "DDL206");
        Assert.Single(result.Schema.Tables[0].Columns);
    }

    [Fact]
    public void PreservesEscapeStringDefaultsContainingAnEscapedQuote()
    {
        const string sql = """CREATE TABLE events (message text DEFAULT E'escaped\'; value' NOT NULL);""";

        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            sql);

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        Assert.Equal("E'escaped\\'; value'", Assert.Single(result.Schema.Tables).Columns[0].DefaultExpression);
    }

    [Fact]
    public void AcceptsCommonConstraintsGeneratedColumnsAndDefaultChanges()
    {
        const string sql = @"
            CREATE TABLE groups (
                id integer PRIMARY KEY,
                code text UNIQUE
            );
            CREATE TABLE members (
                id integer PRIMARY KEY,
                group_id integer REFERENCES groups(id) ON DELETE CASCADE,
                score integer CHECK (score >= 0),
                label text GENERATED ALWAYS AS (group_id::text) STORED,
                CONSTRAINT members_group_fk FOREIGN KEY (group_id) REFERENCES groups(id),
                CONSTRAINT members_score_uq UNIQUE (score)
            );
            ALTER TABLE members ADD CONSTRAINT members_score_check CHECK (score < 1000);
            ALTER TABLE members ALTER COLUMN score SET DEFAULT 0;
            ALTER TABLE members ALTER COLUMN score DROP DEFAULT;
            ALTER TABLE members DROP CONSTRAINT members_score_check;";

        var result = PostgreSqlMigrationAnalyzer.Analyze(
            new DatabaseSchema(Array.Empty<Table>()),
            sql);

        Assert.False(result.HasErrors, string.Join("\n", result.Diagnostics.Select(item => item.ToString())));
        var members = Assert.Single(result.Schema.Tables, item => item.Name == "members");
        Assert.Equal(4, members.Columns.Count);
        Assert.Null(members.Columns.Single(item => item.Name == "score").DefaultExpression);
    }
}
