using CobaltumOrm.Analysis;
using Xunit;

namespace CobaltumOrm.Analysis.Tests;

public sealed class OracleMigrationWriterTests
{
    [Fact]
    public void WritesOracleCreateAddDropRenameAndIdentitySyntax()
    {
        var dialect = new OracleDatabaseDialect();
        var writer = dialect.MigrationSqlWriter;

        var column = writer.FormatColumn("\"id\"", "NUMBER(10,0)", false, true, true);
        Assert.Equal("\"id\" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY", column);
        Assert.Equal(
            "CREATE TABLE \"APP\".\"USERS\" (\"id\" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, \"name\" VARCHAR2(40));",
            writer.CreateTable("\"APP\".\"USERS\"", new[] { column, "\"name\" VARCHAR2(40)" }));
        Assert.Equal(
            "ALTER TABLE \"APP\".\"USERS\" ADD (\"active\" NUMBER(1,0));",
            writer.AddColumn("\"APP\".\"USERS\"", "\"active\" NUMBER(1,0)"));
        Assert.Equal("DROP TABLE \"APP\".\"USERS\";", writer.DropTable("\"APP\".\"USERS\""));
        Assert.Equal(
            "ALTER TABLE \"APP\".\"USERS\" DROP COLUMN \"name\";",
            writer.DropColumn("\"APP\".\"USERS\"", "\"name\""));
        Assert.Equal(
            "ALTER TABLE \"APP\".\"USERS\" RENAME TO \"CUSTOMERS\";",
            writer.RenameTable("\"APP\".\"USERS\"", "\"CUSTOMERS\""));
        Assert.Equal(
            "ALTER TABLE \"APP\".\"USERS\" RENAME COLUMN \"name\" TO \"display_name\";",
            writer.RenameColumn("\"APP\".\"USERS\"", "\"name\"", "\"display_name\""));
    }

    [Fact]
    public void WritesAlterColumnAsOneValidOracleModifyClause()
    {
        var writer = new OracleMigrationSqlWriter();

        Assert.True(writer.TryAlterColumn(
            "\"APP\".\"USERS\"",
            "\"name\"",
            "VARCHAR2(80)",
            false,
            out var sql,
            out var error));
        Assert.Null(error);
        Assert.Equal(
            "ALTER TABLE \"APP\".\"USERS\" MODIFY (\"name\" VARCHAR2(80) NOT NULL);",
            sql);

        Assert.True(writer.TryAlterColumn(
            "\"APP\".\"USERS\"",
            "\"name\"",
            null,
            true,
            out sql,
            out error));
        Assert.Null(error);
        Assert.Equal("ALTER TABLE \"APP\".\"USERS\" MODIFY (\"name\" NULL);", sql);
    }

    [Fact]
    public void ExplainsUnrepresentableAlterColumnRequests()
    {
        var writer = new OracleMigrationSqlWriter();

        Assert.False(writer.TryAlterColumn("\"APP\".\"USERS\"", "\"name\"", null, null, out var sql, out var error));
        Assert.Null(sql);
        Assert.Contains("target SQL type", error);

        Assert.False(writer.TryAlterColumn("\"APP\".\"USERS\"", "\"name\"", "CUSTOM_TYPE", null, out sql, out error));
        Assert.Null(sql);
        Assert.Contains("cannot represent", error);
    }
}
