using System;
using System.Linq;
using System.Threading.Tasks;
using CobaltumOrm.Migrations.PostgreSql;
using CobaltumOrm.Migrations.Tests.Fakes;
using Xunit;

namespace CobaltumOrm.Migrations.Tests;

public sealed class PostgreSqlGenerationTests
{
    [Fact]
    public async Task CreateTableQuotesIdentifiersAndMapsCommonPostgreSqlTypes()
    {
        var connection = new FakeDbConnection();
        var runner = new MigrationRunner(new PostgreSqlMigrationAdapter());

        await runner.MigrateUpAsync(connection, new[] { TestMigrationCatalog.CreateAllTypes });

        var sql = Assert.Single(
            connection.Executions,
            execution => execution.CommandText.StartsWith("CREATE TABLE \"app\"\"data\".", StringComparison.Ordinal));
        Assert.Equal(
            "CREATE TABLE \"app\"\"data\".\"widget\"\"items\" (" +
            "\"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, " +
            "\"small_value\" smallint, " +
            "\"large_value\" bigint, " +
            "\"enabled\" boolean NOT NULL, " +
            "\"amount\" numeric(18,4), " +
            "\"unlimited_amount\" numeric, " +
            "\"single_value\" real, " +
            "\"double_value\" double precision, " +
            "\"label\" text, " +
            "\"code\" character varying(32), " +
            "\"notes\" text, " +
            "\"day\" date, " +
            "\"local_time\" timestamp without time zone, " +
            "\"instant\" timestamp with time zone, " +
            "\"clock\" time without time zone, " +
            "\"external_id\" uuid, " +
            "\"payload\" bytea, " +
            "\"document\" json, " +
            "\"indexed_document\" jsonb);",
            sql.CommandText);
    }

    [Fact]
    public async Task AlterDeleteRenameAndRawSqlShareOneOrderedOperationStream()
    {
        var connection = new FakeDbConnection();
        var runner = new MigrationRunner(new PostgreSqlMigrationAdapter());

        await runner.MigrateUpAsync(connection, new[] { TestMigrationCatalog.ChangeWidgets });

        var commands = connection.Executions
            .Where(execution => execution.TransactionId.HasValue)
            .Where(execution => !execution.CommandText.StartsWith("INSERT INTO", StringComparison.Ordinal))
            .Select(execution => execution.CommandText)
            .ToArray();
        Assert.Equal(
            new[]
            {
                "ALTER TABLE \"app\".\"widgets\" ADD COLUMN \"nickname\" character varying(50);",
                "ALTER TABLE \"app\".\"widgets\" ALTER COLUMN \"created_utc\" TYPE timestamp with time zone;",
                "ALTER TABLE \"app\".\"widgets\" ALTER COLUMN \"created_utc\" SET NOT NULL;",
                "ALTER TABLE \"app\".\"widgets\" ALTER COLUMN \"legacy_code\" DROP NOT NULL;",
                "ALTER TABLE \"app\".\"widgets\" RENAME TO \"accounts\";",
                "ALTER TABLE \"app\".\"accounts\" RENAME COLUMN \"nickname\" TO \"display_name\";",
                "ALTER TABLE \"app\".\"accounts\" DROP COLUMN \"obsolete\";",
                "DROP TABLE \"app\".\"old_widgets\";",
                "UPDATE \"app\".\"accounts\" SET \"display_name\" = 'unknown' WHERE \"display_name\" IS NULL",
            },
            commands);
    }

    [Fact]
    public void HistorySqlIsQuotedAndParameterized()
    {
        var adapter = new PostgreSqlMigrationAdapter();
        IMigrationDatabaseAdapter boundary = adapter;
        var appliedUtc = new DateTimeOffset(2026, 8, 9, 12, 34, 56, TimeSpan.FromHours(9));

        var ensure = boundary.CreateEnsureHistoryTableCommand("meta", "history\"");
        var read = boundary.CreateReadHistoryCommand("meta", "history\"");
        var insert = boundary.CreateInsertHistoryCommand("meta", "history\"", 42, "Create accounts", appliedUtc);
        var delete = boundary.CreateDeleteHistoryCommand("meta", "history\"", 42);
        var exists = ((IMigrationDryRunDatabaseAdapter)adapter)
            .CreateHistoryTableExistsCommand("meta", "history\"");

        Assert.Equal(
            "CREATE TABLE IF NOT EXISTS \"meta\".\"history\"\"\" (\"version\" bigint NOT NULL PRIMARY KEY, " +
            "\"description\" text NOT NULL, \"applied_utc\" timestamp with time zone NOT NULL);",
            ensure.CommandText);
        Assert.Equal(
            "SELECT \"version\" FROM \"meta\".\"history\"\"\" ORDER BY \"version\";",
            read.CommandText);
        Assert.Equal(
            "INSERT INTO \"meta\".\"history\"\"\" (\"version\", \"description\", \"applied_utc\") " +
            "VALUES (@version, @description, @applied_utc);",
            insert.CommandText);
        Assert.Equal(42L, insert.Parameters[0].Value);
        Assert.Equal("Create accounts", insert.Parameters[1].Value);
        Assert.Equal(TimeSpan.Zero, Assert.IsType<DateTimeOffset>(insert.Parameters[2].Value).Offset);
        Assert.Equal(
            "DELETE FROM \"meta\".\"history\"\"\" WHERE \"version\" = @version;",
            delete.CommandText);
        Assert.Equal(42L, delete.Parameters[0].Value);
        Assert.Contains("pg_catalog.pg_class", exists.CommandText, StringComparison.Ordinal);
        Assert.Equal("meta", exists.Parameters[0].Value);
        Assert.Equal("history\"", exists.Parameters[1].Value);
    }

}

[Migration(100, "Create all PostgreSQL types")]
public sealed class CreateAllTypesMigration : Migration
{
    public override void Up()
    {
        Create.Table("widget\"items")
            .InSchema("app\"data")
            .WithColumn("id").AsInt32().Nullable().PrimaryKey().Identity()
            .WithColumn("small_value").AsInt16()
            .WithColumn("large_value").AsInt64()
            .WithColumn("enabled").AsBoolean().NotNullable()
            .WithColumn("amount").AsDecimal(18, 4)
            .WithColumn("unlimited_amount").AsDecimal()
            .WithColumn("single_value").AsFloat()
            .WithColumn("double_value").AsDouble()
            .WithColumn("label").AsString()
            .WithColumn("code").AsString(32)
            .WithColumn("notes").AsText()
            .WithColumn("day").AsDate()
            .WithColumn("local_time").AsDateTime()
            .WithColumn("instant").AsDateTimeOffset()
            .WithColumn("clock").AsTime()
            .WithColumn("external_id").AsGuid()
            .WithColumn("payload").AsBinary()
            .WithColumn("document").AsJson()
            .WithColumn("indexed_document").AsJsonb();
    }

    public override void Down()
    {
        Delete.Table("widget\"items").InSchema("app\"data");
    }
}

[Migration(200, "Change widgets")]
public sealed class ChangeWidgetsMigration : Migration
{
    public override void Up()
    {
        Alter.Table("widgets")
            .InSchema("app")
            .AddColumn("nickname").AsString(50).Nullable()
            .AlterColumn("created_utc").AsDateTimeOffset().NotNullable()
            .AlterColumn("legacy_code").Nullable();
        Rename.Table("widgets").InSchema("app").To("accounts");
        Rename.Column("nickname").OnTable("accounts").InSchema("app").To("display_name");
        Delete.Column("obsolete").FromTable("accounts").InSchema("app");
        Delete.Table("old_widgets").InSchema("app");
        Execute.Sql("UPDATE \"app\".\"accounts\" SET \"display_name\" = 'unknown' WHERE \"display_name\" IS NULL");
    }

    public override void Down()
    {
        Execute.Sql("SELECT 'change widgets down'");
    }
}
