using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace CobaltumOrm.Migrations;

/// <summary>Represents one provider-specific command parameter.</summary>
public sealed class MigrationCommandParameter
{
    /// <summary>Initializes a provider-neutral command parameter.</summary>
    /// <param name="name">The name expected by the generated command text.</param>
    /// <param name="value">The parameter value, or null for a database null.</param>
    public MigrationCommandParameter(string name, object? value)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("A parameter name is required.", nameof(name));
        }

        Name = name;
        Value = value;
    }

    /// <summary>Gets the provider parameter name.</summary>
    public string Name { get; }

    /// <summary>Gets the provider parameter value.</summary>
    public object? Value { get; }
}

/// <summary>Represents SQL and parameter values generated by a database adapter.</summary>
public sealed class MigrationCommand
{
    private readonly ReadOnlyCollection<MigrationCommandParameter> _parameters;

    /// <summary>Initializes a command without parameters.</summary>
    /// <param name="commandText">The SQL command text.</param>
    public MigrationCommand(string commandText)
        : this(commandText, Array.Empty<MigrationCommandParameter>())
    {
    }

    /// <summary>Initializes a command with parameters.</summary>
    /// <param name="commandText">The SQL command text.</param>
    /// <param name="parameters">Parameters in provider binding order.</param>
    public MigrationCommand(string commandText, IEnumerable<MigrationCommandParameter> parameters)
    {
        if (string.IsNullOrWhiteSpace(commandText))
        {
            throw new ArgumentException("Command text is required.", nameof(commandText));
        }

        if (parameters is null)
        {
            throw new ArgumentNullException(nameof(parameters));
        }

        CommandText = commandText;
        var parameterList = new List<MigrationCommandParameter>(parameters);
        if (parameterList.Exists(parameter => parameter is null))
        {
            throw new ArgumentException("The parameter collection cannot contain null values.", nameof(parameters));
        }

        _parameters = parameterList.AsReadOnly();
    }

    /// <summary>Gets the SQL command text.</summary>
    public string CommandText { get; }

    /// <summary>Gets parameters in provider binding order.</summary>
    public IReadOnlyList<MigrationCommandParameter> Parameters => _parameters;
}

/// <summary>
/// Defines the complete database-specific boundary used by the migration runner.
/// Implementations translate operations and history-table actions without requiring
/// the runner to reference a concrete ADO.NET provider.
/// </summary>
public interface IMigrationDatabaseAdapter
{
    /// <summary>Generates one or more commands for a migration operation.</summary>
    /// <param name="operation">The provider-neutral operation.</param>
    /// <returns>Commands in execution order.</returns>
    IReadOnlyList<MigrationCommand> GenerateCommands(MigrationOperation operation);

    /// <summary>Creates the history table if it does not already exist.</summary>
    MigrationCommand CreateEnsureHistoryTableCommand(string? schemaName, string tableName);

    /// <summary>
    /// Creates a command that returns applied versions as signed 64-bit values in
    /// its first result column, ordered from lowest to highest.
    /// </summary>
    MigrationCommand CreateReadHistoryCommand(string? schemaName, string tableName);

    /// <summary>Creates a command that records one successfully applied migration.</summary>
    MigrationCommand CreateInsertHistoryCommand(
        string? schemaName,
        string tableName,
        long version,
        string description,
        DateTimeOffset appliedUtc);

    /// <summary>Creates a command that removes one rolled-back migration version.</summary>
    MigrationCommand CreateDeleteHistoryCommand(string? schemaName, string tableName, long version);
}

/// <summary>
/// Adds the read-only database checks and schema analysis required by migration dry runs.
/// </summary>
public interface IMigrationDryRunDatabaseAdapter
{
    /// <summary>Creates a scalar command that reports whether the migration history table exists.</summary>
    MigrationCommand CreateHistoryTableExistsCommand(string? schemaName, string tableName);

    /// <summary>Builds the schema produced by executing the supplied migration commands in order.</summary>
    MigrationSchema BuildSchema(IReadOnlyList<MigrationCommand> commands);
}
