using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace CobaltumOrm.Migrations;

/// <summary>Identifies a database column type understood by migration adapters.</summary>
public enum MigrationColumnType
{
    /// <summary>No type has been selected.</summary>
    Unspecified = 0,

    /// <summary>A 16-bit signed integer.</summary>
    Int16,

    /// <summary>A 32-bit signed integer.</summary>
    Int32,

    /// <summary>A 64-bit signed integer.</summary>
    Int64,

    /// <summary>A Boolean value.</summary>
    Boolean,

    /// <summary>An arbitrary-precision decimal value.</summary>
    Decimal,

    /// <summary>A single-precision floating-point value.</summary>
    Single,

    /// <summary>A double-precision floating-point value.</summary>
    Double,

    /// <summary>A variable-length string, optionally bounded by a length.</summary>
    String,

    /// <summary>An unbounded text value.</summary>
    Text,

    /// <summary>A calendar date without a time.</summary>
    Date,

    /// <summary>A date and time without a UTC offset.</summary>
    DateTime,

    /// <summary>A date and time representing an instant in time.</summary>
    DateTimeOffset,

    /// <summary>A time of day without a UTC offset.</summary>
    Time,

    /// <summary>A globally unique identifier.</summary>
    Guid,

    /// <summary>Binary data.</summary>
    Binary,

    /// <summary>A JSON document.</summary>
    Json,

    /// <summary>A binary JSON document where the database supports it.</summary>
    JsonBinary,
}

/// <summary>Describes a column used by a create or alter operation.</summary>
public sealed class ColumnDefinition
{
    internal ColumnDefinition(string name, bool isAlteration)
    {
        Name = name;
        IsAlteration = isAlteration;
    }

    /// <summary>Gets the unquoted column name.</summary>
    public string Name { get; }

    /// <summary>Gets the selected logical column type.</summary>
    public MigrationColumnType Type { get; internal set; }

    /// <summary>Gets an optional maximum string length.</summary>
    public int? Length { get; internal set; }

    /// <summary>Gets an optional decimal precision.</summary>
    public int? Precision { get; internal set; }

    /// <summary>Gets an optional decimal scale.</summary>
    public int? Scale { get; internal set; }

    /// <summary>
    /// Gets whether the column accepts nulls. A null value means an alter-column
    /// expression did not request a nullability change.
    /// </summary>
    public bool? IsNullable { get; internal set; }

    /// <summary>Gets whether the column is an inline primary key.</summary>
    public bool IsPrimaryKey { get; internal set; }

    /// <summary>Gets whether values are generated by the database.</summary>
    public bool IsIdentity { get; internal set; }

    internal bool IsAlteration { get; }
}

/// <summary>Base type for operations emitted by a <see cref="Migration"/>.</summary>
public abstract class MigrationOperation
{
    private protected MigrationOperation()
    {
    }
}

/// <summary>Creates a table and its columns.</summary>
public sealed class CreateTableOperation : MigrationOperation
{
    private readonly List<ColumnDefinition> _columns = new List<ColumnDefinition>();
    private readonly ReadOnlyCollection<ColumnDefinition> _readOnlyColumns;

    internal CreateTableOperation(string tableName)
    {
        TableName = tableName;
        _readOnlyColumns = _columns.AsReadOnly();
    }

    /// <summary>Gets the unquoted table name.</summary>
    public string TableName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }

    /// <summary>Gets the columns in declaration order.</summary>
    public IReadOnlyList<ColumnDefinition> Columns => _readOnlyColumns;

    internal ColumnDefinition AddColumn(string name)
    {
        var column = new ColumnDefinition(name, false);
        _columns.Add(column);
        return column;
    }
}

/// <summary>Adds a column to an existing table.</summary>
public sealed class AddColumnOperation : MigrationOperation
{
    internal AddColumnOperation(string tableName, ColumnDefinition column)
    {
        TableName = tableName;
        Column = column;
    }

    /// <summary>Gets the unquoted table name.</summary>
    public string TableName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }

    /// <summary>Gets the column being added.</summary>
    public ColumnDefinition Column { get; }
}

/// <summary>Changes a column type and/or nullability.</summary>
public sealed class AlterColumnOperation : MigrationOperation
{
    internal AlterColumnOperation(string tableName, ColumnDefinition column)
    {
        TableName = tableName;
        Column = column;
    }

    /// <summary>Gets the unquoted table name.</summary>
    public string TableName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }

    /// <summary>Gets the requested column changes.</summary>
    public ColumnDefinition Column { get; }
}

/// <summary>Drops a table.</summary>
public sealed class DeleteTableOperation : MigrationOperation
{
    internal DeleteTableOperation(string tableName)
    {
        TableName = tableName;
    }

    /// <summary>Gets the unquoted table name.</summary>
    public string TableName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }
}

/// <summary>Drops a column from a table.</summary>
public sealed class DeleteColumnOperation : MigrationOperation
{
    internal DeleteColumnOperation(string tableName, string columnName)
    {
        TableName = tableName;
        ColumnName = columnName;
    }

    /// <summary>Gets the unquoted table name.</summary>
    public string TableName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }

    /// <summary>Gets the unquoted column name.</summary>
    public string ColumnName { get; }
}

/// <summary>Renames a table.</summary>
public sealed class RenameTableOperation : MigrationOperation
{
    internal RenameTableOperation(string oldName, string newName)
    {
        OldName = oldName;
        NewName = newName;
    }

    /// <summary>Gets the current unquoted table name.</summary>
    public string OldName { get; }

    /// <summary>Gets the new unquoted table name.</summary>
    public string NewName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }
}

/// <summary>Renames a column.</summary>
public sealed class RenameColumnOperation : MigrationOperation
{
    internal RenameColumnOperation(string tableName, string oldName, string newName)
    {
        TableName = tableName;
        OldName = oldName;
        NewName = newName;
    }

    /// <summary>Gets the unquoted table name.</summary>
    public string TableName { get; }

    /// <summary>Gets the optional unquoted schema name.</summary>
    public string? SchemaName { get; internal set; }

    /// <summary>Gets the current unquoted column name.</summary>
    public string OldName { get; }

    /// <summary>Gets the new unquoted column name.</summary>
    public string NewName { get; }
}

/// <summary>Executes SQL supplied directly by the migration author.</summary>
public sealed class ExecuteSqlOperation : MigrationOperation
{
    internal ExecuteSqlOperation(string sql)
    {
        Sql = sql;
    }

    /// <summary>Gets the SQL text exactly as supplied.</summary>
    public string Sql { get; }
}
