using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CobaltumOrm.Migrations;
using CobaltumOrm.Migrations.Oracle;
using Xunit;

namespace CobaltumOrm.Oracle.Tests;

public sealed class OracleMigrationAdapterTests
{
    [Fact]
    public async Task CreateTableQuotesNamesAndMapsOracleStorageTypes()
    {
        var connection = new RecordingDbConnection { HistoryTableExists = false };
        await new MigrationRunner(new OracleMigrationAdapter()).MigrateUpAsync(
            connection,
            new[] { MigrationInfo.Create<CreateAllOracleTypesMigration>(1, "Create all Oracle types") });

        var create = Assert.Single(
            connection.Executions,
            execution => execution.CommandText.StartsWith("CREATE TABLE \"app\"\"schema\".", StringComparison.Ordinal));
        Assert.Equal(
            "CREATE TABLE \"app\"\"schema\".\"widget\"\"items\" (" +
            "\"id\" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, " +
            "\"small_value\" NUMBER(5,0), " +
            "\"large_value\" NUMBER(19,0), " +
            "\"enabled\" NUMBER(1,0) NOT NULL, " +
            "\"amount\" NUMBER(18,4), " +
            "\"unlimited_amount\" NUMBER, " +
            "\"single_value\" BINARY_FLOAT, " +
            "\"double_value\" BINARY_DOUBLE, " +
            "\"label\" CLOB, " +
            "\"code\" VARCHAR2(32), " +
            "\"notes\" CLOB, " +
            "\"day\" DATE, " +
            "\"local_time\" TIMESTAMP, " +
            "\"instant\" TIMESTAMP WITH TIME ZONE, " +
            "\"clock\" TIMESTAMP, " +
            "\"external_id\" RAW(16), " +
            "\"payload\" BLOB, " +
            "\"document\" CLOB, " +
            "\"indexed_document\" BLOB)",
            create.CommandText);
    }

    [Fact]
    public async Task OracleAlterDropRenameAndRawCommandsUseOracleSyntax()
    {
        var connection = new RecordingDbConnection { HistoryTableExists = false };
        await new MigrationRunner(new OracleMigrationAdapter()).MigrateUpAsync(
            connection,
            new[] { MigrationInfo.Create<ChangeOracleTablesMigration>(2, "Change Oracle tables") });

        var commands = connection.Executions
            .Where(execution => execution.TransactionId.HasValue)
            .Where(execution => !execution.CommandText.StartsWith("INSERT INTO", StringComparison.Ordinal))
            .Select(execution => execution.CommandText)
            .ToArray();
        Assert.Equal(
            new[]
            {
                "ALTER TABLE \"app\".\"widgets\" ADD (\"nickname\" VARCHAR2(50))",
                "ALTER TABLE \"app\".\"widgets\" MODIFY (\"created_utc\" TIMESTAMP WITH TIME ZONE NOT NULL)",
                "ALTER TABLE \"app\".\"widgets\" MODIFY (\"legacy_code\" NULL)",
                "ALTER TABLE \"app\".\"widgets\" RENAME TO \"accounts\"",
                "ALTER TABLE \"app\".\"accounts\" RENAME COLUMN \"nickname\" TO \"display_name\"",
                "ALTER TABLE \"app\".\"accounts\" DROP COLUMN \"obsolete\"",
                "DROP TABLE \"app\".\"old_widgets\"",
                "UPDATE \"app\".\"accounts\" SET \"display_name\" = 'unknown' WHERE \"display_name\" IS NULL",
            },
            commands);
    }

    [Fact]
    public void HistoryCommandsUseOracleIdentifiersAndColonParameters()
    {
        var adapter = new OracleMigrationAdapter();
        IMigrationDatabaseAdapter boundary = adapter;
        var appliedUtc = new DateTimeOffset(2026, 8, 9, 12, 34, 56, TimeSpan.FromHours(9));

        var ensure = boundary.CreateEnsureHistoryTableCommand("meta", "history\"");
        var read = boundary.CreateReadHistoryCommand("meta", "history\"");
        var insert = boundary.CreateInsertHistoryCommand("meta", "history\"", 42, "Create accounts", appliedUtc);
        var delete = boundary.CreateDeleteHistoryCommand("meta", "history\"", 42);
        var exists = adapter.CreateHistoryTableExistsCommand("meta", "history\"");

        Assert.Contains("EXECUTE IMMEDIATE", ensure.CommandText, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE \"meta\".\"history\"\"\"", ensure.CommandText, StringComparison.Ordinal);
        Assert.Contains("IF SQLCODE <> -955", ensure.CommandText, StringComparison.Ordinal);
        Assert.DoesNotContain("-942", ensure.CommandText, StringComparison.Ordinal);
        Assert.Equal(
            "SELECT \"version\" FROM \"meta\".\"history\"\"\" ORDER BY \"version\"",
            read.CommandText);
        Assert.Equal(
            "INSERT INTO \"meta\".\"history\"\"\" (\"version\", \"description\", \"applied_utc\") " +
            "VALUES (:version, :description, :applied_utc)",
            insert.CommandText);
        Assert.Equal(42L, insert.Parameters[0].Value);
        Assert.Equal("Create accounts", insert.Parameters[1].Value);
        Assert.Equal(TimeSpan.Zero, Assert.IsType<DateTimeOffset>(insert.Parameters[2].Value).Offset);
        Assert.Equal(
            "DELETE FROM \"meta\".\"history\"\"\" WHERE \"version\" = :version",
            delete.CommandText);
        Assert.Equal(42L, delete.Parameters[0].Value);
        Assert.Contains("ALL_TABLES", exists.CommandText, StringComparison.Ordinal);
        Assert.Contains("SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')", exists.CommandText, StringComparison.Ordinal);
        Assert.Equal("meta", exists.Parameters[0].Value);
        Assert.Equal("history\"", exists.Parameters[1].Value);
    }

    [Fact]
    public void DefaultSchemaIsUnqualifiedAndIdentifierQuotesAreEscaped()
    {
        var adapter = new OracleMigrationAdapter();
        Assert.Equal("\"table.name\"", adapter.QuoteIdentifier("table.name"));
        Assert.Equal("\"schema\".\"table\"", adapter.QuoteQualifiedName("schema", "table"));
        Assert.Equal("\"table\"", adapter.QuoteQualifiedName(null, "table"));
        Assert.Equal("\"a\"\"b\"", adapter.QuoteIdentifier("a\"b"));
    }

    [Fact]
    public void BuildSchemaReconstructsGeneratedCreateAlterDropAndRenameCommands()
    {
        var adapter = new OracleMigrationAdapter();
        var schema = adapter.BuildSchema(new[]
        {
            new MigrationCommand(
                "CREATE TABLE \"app\".\"users\" (" +
                "\"id\" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, " +
                "\"name\" VARCHAR2(50), \"created\" TIMESTAMP WITH TIME ZONE)"),
            new MigrationCommand("ALTER TABLE \"app\".\"users\" ADD (\"active\" NUMBER(1,0) NOT NULL)"),
            new MigrationCommand("ALTER TABLE \"app\".\"users\" MODIFY (\"name\" CLOB NOT NULL)"),
            new MigrationCommand("ALTER TABLE \"app\".\"users\" MODIFY (\"created\" NULL)"),
            new MigrationCommand("ALTER TABLE \"app\".\"users\" RENAME COLUMN \"name\" TO \"display_name\""),
            new MigrationCommand("ALTER TABLE \"app\".\"users\" RENAME TO \"accounts\""),
            new MigrationCommand("UPDATE \"app\".\"accounts\" SET \"display_name\" = 'unknown'"),
            new MigrationCommand("ALTER TABLE \"app\".\"accounts\" DROP COLUMN \"active\""),
        });

        var table = Assert.Single(schema.Tables);
        Assert.Equal("app", table.SchemaName);
        Assert.Equal("accounts", table.Name);
        Assert.Equal(new[] { "id", "display_name", "created" }, table.Columns.Select(column => column.Name));
        Assert.Equal("NUMBER(10,0)", table.Columns[0].SqlType);
        Assert.True(table.Columns[0].IsIdentity);
        Assert.True(table.Columns[0].IsPrimaryKey);
        Assert.False(table.Columns[0].IsNullable);
        Assert.Equal("CLOB", table.Columns[1].SqlType);
        Assert.False(table.Columns[1].IsNullable);
        Assert.True(table.Columns[2].IsNullable);
    }

    [Fact]
    public void BuildSchemaSupportsFlywayOracleHistoryTableAndIgnoresDataStatements()
    {
        var adapter = new OracleMigrationAdapter();
        var schema = adapter.BuildSchema(new[]
        {
            new MigrationCommand(@"
                -- Oracle Flyway history table
                CREATE TABLE ""flyway_schema_history"" (
                    ""installed_rank"" NUMBER(10) NOT NULL,
                    ""version"" VARCHAR2(50),
                    ""description"" VARCHAR2(200) NOT NULL,
                    ""type"" VARCHAR2(20) NOT NULL,
                    ""script"" VARCHAR2(1000) NOT NULL,
                    ""checksum"" NUMBER(10),
                    ""installed_by"" VARCHAR2(100) NOT NULL,
                    ""installed_on"" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    ""execution_time"" NUMBER(10) NOT NULL,
                    ""success"" NUMBER(1) NOT NULL,
                    CONSTRAINT ""flyway_schema_history_pk"" PRIMARY KEY (""installed_rank"")
                );
                INSERT INTO ""flyway_schema_history"" (""installed_rank"") VALUES (1);
                UPDATE ""flyway_schema_history"" SET ""success"" = 1;
                DELETE FROM ""flyway_schema_history"" WHERE ""installed_rank"" = 1;
            "),
        });

        var table = Assert.Single(schema.Tables);
        Assert.Null(table.SchemaName);
        Assert.Equal("flyway_schema_history", table.Name);
        Assert.Equal(10, table.Columns.Count);
        Assert.Equal("NUMBER(10)", table.Columns[0].SqlType);
        Assert.True(table.Columns[0].IsPrimaryKey);
        Assert.False(table.Columns[0].IsNullable);
        Assert.Equal("SYSTIMESTAMP", table.Columns[7].DefaultExpression);
    }

    [Theory]
    [InlineData("CREATE VIEW \"users_view\" AS SELECT 1 FROM DUAL")]
    [InlineData("CREATE INDEX \"users_idx\" ON \"users\" (\"id\")")]
    [InlineData("ALTER TABLE \"users\" ADD CONSTRAINT \"fk\" FOREIGN KEY (\"id\") REFERENCES \"other\" (\"id\")")]
    public void BuildSchemaRejectsUnsupportedSchemaChangingStatements(string sql)
    {
        var exception = Assert.Throws<MigrationValidationException>(
            () => new OracleMigrationAdapter().BuildSchema(new[] { new MigrationCommand(sql) }));
        Assert.Contains("Final schema could not be determined", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public async Task DryRunBuildsFinalOracleSchemaWithoutApplyingCommands()
    {
        var connection = new RecordingDbConnection { HistoryTableExists = false };
        var dryRun = await new MigrationRunner(new OracleMigrationAdapter()).DryRunUpAsync(
            connection,
            new[] { MigrationInfo.Create<DryRunOracleMigration>(3, "Dry-run Oracle migration") });

        Assert.DoesNotContain(connection.Executions, execution => execution.TransactionId.HasValue);
        var table = Assert.Single(dryRun.FinalSchema.Tables);
        Assert.Equal("preview_users", table.Name);
        Assert.Equal(new[] { "id", "name" }, table.Columns.Select(column => column.Name));
        Assert.Equal("NUMBER(19,0)", table.Columns[0].SqlType);
        Assert.True(table.Columns[0].IsIdentity);
    }

    [Fact]
    public async Task InvalidColumnDeclarationsAreRejectedBeforeExecution()
    {
        await Assert.ThrowsAsync<MigrationValidationException>(() => RunMigration(
            MigrationInfo.Create<MissingTypeMigration>(4, "Missing type")));
        await Assert.ThrowsAsync<MigrationValidationException>(() => RunMigration(
            MigrationInfo.Create<DuplicateColumnMigration>(5, "Duplicate column")));
        await Assert.ThrowsAsync<MigrationValidationException>(() => RunMigration(
            MigrationInfo.Create<InvalidIdentityMigration>(6, "Invalid identity")));
        await Assert.ThrowsAsync<MigrationValidationException>(() => RunMigration(
            MigrationInfo.Create<CompositePrimaryKeyMigration>(7, "Composite primary key")));
    }

    private static async Task RunMigration(MigrationInfo migration)
    {
        await new MigrationRunner(new OracleMigrationAdapter()).MigrateUpAsync(
            new RecordingDbConnection { HistoryTableExists = false },
            new[] { migration });
    }
}

[Migration(1, "Create all Oracle types")]
public sealed class CreateAllOracleTypesMigration : Migration
{
    public override void Up()
    {
        Create.Table("widget\"items")
            .InSchema("app\"schema")
            .WithColumn("id").AsInt32().Nullable().PrimaryKey().Identity()
            .WithColumn("small_value").AsInt16()
            .WithColumn("large_value").AsInt64()
            .WithColumn("enabled").AsBoolean().NotNullable()
            .WithColumn("amount").AsDecimal(18, 4)
            .WithColumn("unlimited_amount").AsDecimal()
            .WithColumn("single_value").AsFloat()
            .WithColumn("double_value").AsDouble()
            .WithColumn("label").AsString()
            .WithColumn("code").AsString(32)
            .WithColumn("notes").AsText()
            .WithColumn("day").AsDate()
            .WithColumn("local_time").AsDateTime()
            .WithColumn("instant").AsDateTimeOffset()
            .WithColumn("clock").AsTime()
            .WithColumn("external_id").AsGuid()
            .WithColumn("payload").AsBinary()
            .WithColumn("document").AsJson()
            .WithColumn("indexed_document").AsJsonb();
    }

    public override void Down() => Delete.Table("widget\"items").InSchema("app\"schema");
}

[Migration(2, "Change Oracle tables")]
public sealed class ChangeOracleTablesMigration : Migration
{
    public override void Up()
    {
        Alter.Table("widgets")
            .InSchema("app")
            .AddColumn("nickname").AsString(50).Nullable()
            .AlterColumn("created_utc").AsDateTimeOffset().NotNullable()
            .AlterColumn("legacy_code").Nullable();
        Rename.Table("widgets").InSchema("app").To("accounts");
        Rename.Column("nickname").OnTable("accounts").InSchema("app").To("display_name");
        Delete.Column("obsolete").FromTable("accounts").InSchema("app");
        Delete.Table("old_widgets").InSchema("app");
        Execute.Sql("UPDATE \"app\".\"accounts\" SET \"display_name\" = 'unknown' WHERE \"display_name\" IS NULL");
    }

    public override void Down() => Execute.Sql("SELECT 'change tables down'");
}

[Migration(3, "Dry-run Oracle migration")]
public sealed class DryRunOracleMigration : Migration
{
    public override void Up()
    {
        Create.Table("preview_users")
            .WithColumn("id").AsInt64().Identity().PrimaryKey()
            .WithColumn("name").AsString(80).Nullable();
        Execute.Sql("UPDATE \"preview_users\" SET \"name\" = 'preview'");
    }

    public override void Down() => Delete.Table("preview_users");
}

[Migration(4, "Missing type")]
public sealed class MissingTypeMigration : Migration
{
    public override void Up() => Create.Table("missing_type").WithColumn("id");
    public override void Down() => Delete.Table("missing_type");
}

[Migration(5, "Duplicate column")]
public sealed class DuplicateColumnMigration : Migration
{
    public override void Up() => Create.Table("duplicate").WithColumn("id").AsInt32().WithColumn("id").AsInt32();
    public override void Down() => Delete.Table("duplicate");
}

[Migration(6, "Invalid identity")]
public sealed class InvalidIdentityMigration : Migration
{
    public override void Up() => Create.Table("invalid_identity").WithColumn("value").AsString(20).Identity();
    public override void Down() => Delete.Table("invalid_identity");
}

[Migration(7, "Composite primary key")]
public sealed class CompositePrimaryKeyMigration : Migration
{
    public override void Up() => Create.Table("composite")
        .WithColumn("left").AsInt32().PrimaryKey()
        .WithColumn("right").AsInt32().PrimaryKey();

    public override void Down() => Delete.Table("composite");
}

#pragma warning disable CS8765

internal sealed class RecordingDbConnection : DbConnection
{
    private ConnectionState _state = ConnectionState.Closed;
    private int _nextTransactionId;

    internal bool HistoryTableExists { get; set; } = true;
    internal List<RecordingExecution> Executions { get; } = new List<RecordingExecution>();

    public override string ConnectionString { get; set; } = string.Empty;
    public override string Database => "oracle";
    public override string DataSource => "oracle";
    public override string ServerVersion => "1";
    public override ConnectionState State => _state;

    public override void ChangeDatabase(string databaseName)
    {
    }

    public override void Close() => _state = ConnectionState.Closed;
    public override void Open() => _state = ConnectionState.Open;

    public override Task OpenAsync(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        _state = ConnectionState.Open;
        return Task.CompletedTask;
    }

    protected override DbTransaction BeginDbTransaction(IsolationLevel isolationLevel) =>
        new RecordingDbTransaction(this, ++_nextTransactionId, isolationLevel);

    protected override DbCommand CreateDbCommand() => new RecordingDbCommand(this);

    internal int ExecuteNonQuery(RecordingDbCommand command, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        Record(command, false);
        return 1;
    }

    internal object ExecuteScalar(RecordingDbCommand command, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        Record(command, false);
        return HistoryTableExists;
    }

    internal DbDataReader ExecuteReader(RecordingDbCommand command, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        Record(command, true);
        var table = new DataTable();
        table.Columns.Add("version", typeof(long));
        return table.CreateDataReader();
    }

    private void Record(RecordingDbCommand command, bool reader)
    {
        var parameters = command.Parameters.Cast<DbParameter>()
            .ToDictionary(parameter => parameter.ParameterName, parameter => parameter.Value);
        Executions.Add(new RecordingExecution(
            command.CommandText,
            parameters,
            (command.Transaction as RecordingDbTransaction)?.Id,
            reader));
    }
}

internal sealed class RecordingDbTransaction : DbTransaction
{
    internal RecordingDbTransaction(RecordingDbConnection connection, int id, IsolationLevel isolationLevel)
    {
        DbConnectionValue = connection;
        Id = id;
        IsolationLevel = isolationLevel;
    }

    internal int Id { get; }
    internal RecordingDbConnection DbConnectionValue { get; }
    public override IsolationLevel IsolationLevel { get; }
    protected override DbConnection DbConnection => DbConnectionValue;
    public override void Commit()
    {
    }

    public override void Rollback()
    {
    }
}

internal sealed class RecordingDbCommand : DbCommand
{
    private readonly RecordingDbConnection _connection;
    private readonly RecordingDbParameterCollection _parameters = new RecordingDbParameterCollection();

    internal RecordingDbCommand(RecordingDbConnection connection) => _connection = connection;

    public override string CommandText { get; set; } = string.Empty;
    public override int CommandTimeout { get; set; }
    public override CommandType CommandType { get; set; } = CommandType.Text;
    public override bool DesignTimeVisible { get; set; }
    public override UpdateRowSource UpdatedRowSource { get; set; }
    internal new RecordingDbTransaction? Transaction => (RecordingDbTransaction?)DbTransaction;
    protected override DbConnection DbConnection
    {
        get => _connection;
        set => throw new NotSupportedException();
    }

    protected override DbParameterCollection DbParameterCollection => _parameters;
    protected override DbTransaction? DbTransaction { get; set; }
    public override void Cancel()
    {
    }

    public override int ExecuteNonQuery() => _connection.ExecuteNonQuery(this, CancellationToken.None);
    public override Task<int> ExecuteNonQueryAsync(CancellationToken cancellationToken) =>
        Task.FromResult(_connection.ExecuteNonQuery(this, cancellationToken));
    public override object ExecuteScalar() => _connection.ExecuteScalar(this, CancellationToken.None);
    public override Task<object?> ExecuteScalarAsync(CancellationToken cancellationToken) =>
        Task.FromResult<object?>(_connection.ExecuteScalar(this, cancellationToken));
    public override void Prepare()
    {
    }

    protected override DbParameter CreateDbParameter() => new RecordingDbParameter();
    protected override DbDataReader ExecuteDbDataReader(CommandBehavior behavior) =>
        _connection.ExecuteReader(this, CancellationToken.None);
    protected override Task<DbDataReader> ExecuteDbDataReaderAsync(
        CommandBehavior behavior,
        CancellationToken cancellationToken) =>
        Task.FromResult(_connection.ExecuteReader(this, cancellationToken));
}

internal sealed class RecordingDbParameter : DbParameter
{
    public override DbType DbType { get; set; }
    public override ParameterDirection Direction { get; set; } = ParameterDirection.Input;
    public override bool IsNullable { get; set; }
    public override string ParameterName { get; set; } = string.Empty;
    public override int Size { get; set; }
    public override string SourceColumn { get; set; } = string.Empty;
    public override bool SourceColumnNullMapping { get; set; }
    public override object? Value { get; set; }
    public override void ResetDbType()
    {
    }
}

internal sealed class RecordingDbParameterCollection : DbParameterCollection
{
    private readonly List<DbParameter> _items = new List<DbParameter>();
    public override int Count => _items.Count;
    public override object SyncRoot => ((ICollection)_items).SyncRoot;
    public override int Add(object value)
    {
        _items.Add((DbParameter)value);
        return _items.Count - 1;
    }

    public override void AddRange(Array values)
    {
        foreach (var value in values)
        {
            Add(value!);
        }
    }

    public override void Clear() => _items.Clear();
    public override bool Contains(object value) => _items.Contains((DbParameter)value);
    public override bool Contains(string value) => IndexOf(value) >= 0;
    public override void CopyTo(Array array, int index) => ((ICollection)_items).CopyTo(array, index);
    public override IEnumerator GetEnumerator() => _items.GetEnumerator();
    public override int IndexOf(object value) => _items.IndexOf((DbParameter)value);
    public override int IndexOf(string parameterName) =>
        _items.FindIndex(parameter => string.Equals(parameter.ParameterName, parameterName, StringComparison.Ordinal));
    public override void Insert(int index, object value) => _items.Insert(index, (DbParameter)value);
    public override void Remove(object value) => _items.Remove((DbParameter)value);
    public override void RemoveAt(int index) => _items.RemoveAt(index);
    public override void RemoveAt(string parameterName) => _items.RemoveAt(IndexOf(parameterName));
    protected override DbParameter GetParameter(int index) => _items[index];
    protected override DbParameter GetParameter(string parameterName)
    {
        var index = IndexOf(parameterName);
        return index < 0 ? throw new IndexOutOfRangeException(parameterName) : _items[index];
    }

    protected override void SetParameter(int index, DbParameter value) => _items[index] = value;
    protected override void SetParameter(string parameterName, DbParameter value)
    {
        var index = IndexOf(parameterName);
        if (index < 0)
        {
            _items.Add(value);
        }
        else
        {
            _items[index] = value;
        }
    }
}

internal sealed class RecordingExecution
{
    internal RecordingExecution(
        string commandText,
        IReadOnlyDictionary<string, object?> parameters,
        int? transactionId,
        bool isReader)
    {
        CommandText = commandText;
        Parameters = parameters;
        TransactionId = transactionId;
        IsReader = isReader;
    }

    internal string CommandText { get; }
    internal IReadOnlyDictionary<string, object?> Parameters { get; }
    internal int? TransactionId { get; }
    internal bool IsReader { get; }
}

#pragma warning restore CS8765
